### ISSUE TITLE
pytorch issue

### ISSUE THREAD

**Issue by HarbingerOfHell** [GauthierDmn/question_generation#1]
I've been trying to run your project with all the same data files that you have instructed. I've been getting the following error: 

`Traceback (most recent call last):

  File "train.py", line 135, in <module>

    pred = model(sentence, len_sentence, question, answer)

  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__

    result = self.forward(*input, **kwargs)

  File "/home/quilllionzml/question_generation/model.py", line 29, in forward

    enc_output, enc_hidden = self.enc(sentence, sentence_len, answer)

  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__

    result = self.forward(*input, **kwargs)

  File "/home/quilllionzml/question_generation/layers.py", line 48, in forward

    x = self.embedding(x, y)

  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__

    result = self.forward(*input, **kwargs)

  File "/home/quilllionzml/question_generation/layers.py", line 20, in forward

    f_emb = self.f_embed(y)

  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__

    result = self.forward(*input, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/sparse.py", line 117, in forward

    self.norm_type, self.scale_grad_by_freq, self.sparse)

  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1506, in embedding

    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:193`

Could you help with this?
Side note: what are in_vocab_size and out_vocab_size?

**Comment by GauthierDmn** [comment]
Hi @HarbingerOfHell , it seems that the size of your vocabulary is larger than the size of your embedding matrix. You may be able to see it if you print the maximum value of your input sequence, and the shape of your embedding matrix.

The second question you are asking may be part of the solution to debug your problem: in_vocab_size if the size of the input vocabulary, meaning that all your input words will be mapped to an integer in range(0, in_vocab_size). Similarly, out_vocab_size is the size of the output vocabulary.

Let me know how it goes.

Gauthier

**Comment by HarbingerOfHell** [comment]
Hi @GauthierDmn , thanks for the prompt reply. I have changes in_vocab_size to reflect the vocabulary but I keep getting the same error. Since this error is present in f_embed, could you clarify what it is? Since it is a 4x2 embedding, I have been unable to figure out it's purpose.

**Comment by GauthierDmn** [comment]
Hi @HarbingerOfHell ,

f_emb is the embedding matrix for the features associated to the answer to the question you want to generate. If you look at your training sentences you created with the `make_dataset.py` file, you normally have `0` and `1` separated by a `￨` symbol next to each word. The `0` means that the word is not part of the answer, the `1` on the other hand are part of the answer.

A typical example of a sentence and a question pair for training the model is:

S: Napoleon￨0 's￨0 large￨0 empire￨0 collapsed￨0 in￨1 1815￨1 .￨0
Q: When did Napoleon 's empire collapse ?

Now during training, `0` and `1` are represented as vectors of size answer_embedding_size the same way as words.

The number of embedding vectors, 4 in this case, comes from the fact that I am using the same padding index as word vectors (variable padding_index), which is 1. So my feature `0` (no answer token) will have index 2 and my feature `1` (answer token) will have index 3. Which corresponds to an embedding matrix of size (4, answer_embedding_size) at the end.

To understand why you are getting this error, comment the line dealing with the model in your `train.py` file, and print the values of the variable `answer` in your batch. If everything works well, you normally have tensors with values 1 (padding index), 2 (no answer token) and 3 (answer token). Since you are getting this error, I guess you have larger values than this?

I let you investigate where it comes from.

**Comment by HarbingerOfHell** [comment]
Thank you very much for your help! I've managed to fix this by increasing the f_emb embedding size.
